In [1]:
import numpy as np


In [2]:
a=np.array([1,3,5],dtype='int16')
print(a)
b=np.array([[1.0,2.0,3.0],[5.0,8.0,6.0]])
print(b)

[1 3 5]
[[1. 2. 3.]
 [5. 8. 6.]]


In [3]:
#Get Dimension of numpy array
print(a.ndim)

#Get shape
print(b.shape)

#Get type
print(a.dtype)

#Get size
print(a.itemsize)

#Get total size = total no. of elements size
print(a.size*a.itemsize) #==a.nbytes


1
(2, 3)
int16
2
6


In [4]:
#Accessing/Changing specific elements, rows, columns, etc.
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# Get a specific element {r,c}
a[1,5]

# Get a specific column
a[:,2]

# Get a specific row
a[0,:]

# Getting a little more fancy {starindex:endindex:stepsize}
a[0,1:6:2]

# Getting a little more fancy {starindex:endindex:stepsize}
a[0,1:-2:2]

a[1,5]=20
print(a)

a[:,2]=5
print(a)

a[:,2]=[1,2]
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [5]:
#3-d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

# Get specific element (work outside in)
b[0,1,1]

# Get specific element (work outside in) *fancy*
b[:,1,:]

# replace
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [6]:
# Initialize all 0s matrix
np.zeros((2,3))

# All 1s matrix
np.ones((4,2,2),dtype='int32')

# Initialize all 0s matrix
np.zeros((2,3,3))

# Any other number
np.full((2,2),99)

# Any other number (full_like)
np.full_like(a,4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [7]:
# Random Decimal Number //random numbers between zeero and one we don't pass tubules
np.random.rand(4,2)

np.random.random_sample(a.shape)

# Random integer values
np.random.randint(-2,9, size=(3,3))

array([[-1, -1,  3],
       [ 0,  4,  0],
       [ 8, -2,  3]])

In [8]:
# Identity Matrix
np.identity(5)

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

# Example
arr= np.ones((5,5),dtype='int32')
print(arr)
z= np.zeros((3,3))
z[1,1]=9
print(z)
arr[1:4,1:4]=z
print(arr)

[[1 1 1 2 2 2 3 3 3]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [9]:
#### Be careful when copying arrays!!
a = np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [13]:
# Mathematics
a = np.array([1,2,3,4])
a += 2
#a *= 2
print(a ** 2)
print(a)
b = np.array([1,0,1,0])
print(a+b)

[ 9 16 25 36]
[3 4 5 6]
[4 4 6 6]


In [11]:
# Take the sin of all the values
np.sin(a)
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [12]:
# Linear algebra
a= np.ones((2,3))
print(a)

b= np.full((3,2),2)
print(b)

print(np.matmul(a,b))


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [14]:
# Determinant of a matrix
c = np.identity(3)
print(np.linalg.det(c))

1.0


In [15]:
#### Statistics

stats = np.array([[1,2,3],[4,5,6]])
print(np.min(stats, axis=1)) # axis=0 is the min row in both row & axis =1 is the min in each row
np.max(stats)

print(np.sum(stats, axis=0))

[1 4]
[5 7 9]


In [16]:
# Reorganizing arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after= before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Vertically Stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [18]:
# Horizontal stack
h1 = np.ones([2,4])
h2 = np.zeros([2,2])

print(np.hstack([h1,h2]))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [19]:
###  Miscellaneous
Load Data from File
filedata = np.genfromtxt('data.txt' , delimiter=',')
filedata.astype('int32')
filedata = filedata.astype('int32')

SyntaxError: invalid syntax (<ipython-input-19-3bc196de5248>, line 2)

In [20]:
#### Advanced indexing and boolean masking
filedata>50
filedata[filedata>50]  #returns the values greater than 50
## You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,9]] # this returns the value of index written
np.any(filedata>50, axis=0) #what columns have value greater than 50
np.all(filedata>50,axis=0) #all data in same column must be greater than 50
#axis=1 is rows
((filedata > 50) & (filedata<100))
(~(filedata > 50) & (filedata<100))

#indexing examples
#a[2:4,0:2]
#for ladder shape indexing 
#a[[0,1,2,3],[1,2,3,4]] 
#a[[0,4,5],3:]

NameError: name 'filedata' is not defined